package com.local.service.km.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2022-07-29T15:15:22.772+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://webservice.review.km.kmss.landray.com/", name = "IKmReviewWebserviceService")
@XmlSeeAlso({com.local.service.km.webservice.ObjectFactory.class})
public interface IKmReviewWebserviceService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "approveProcess", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.local.service.km.webservice.ApproveProcess")
    @WebMethod
    @ResponseWrapper(localName = "approveProcessResponse", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.local.service.km.webservice.ApproveProcessResponse")
    public java.lang.String approveProcess(
        @WebParam(name = "arg0", targetNamespace = "")
        com.local.service.km.webservice.KmReviewParamterForm arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateReviewInfo", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.local.service.km.webservice.UpdateReviewInfo")
    @WebMethod
    @ResponseWrapper(localName = "updateReviewInfoResponse", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.local.service.km.webservice.UpdateReviewInfoResponse")
    public java.lang.String updateReviewInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        com.local.service.km.webservice.KmReviewParamterForm arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addReview", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.local.service.km.webservice.AddReview")
    @WebMethod
    @ResponseWrapper(localName = "addReviewResponse", targetNamespace = "http://webservice.review.km.kmss.landray.com/", className = "com.local.service.km.webservice.AddReviewResponse")
    public java.lang.String addReview(
        @WebParam(name = "arg0", targetNamespace = "")
        com.local.service.km.webservice.KmReviewParamterForm arg0
    ) throws Exception_Exception;
}
