
package org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.4
 * Wed Jun 29 18:16:39 CST 2022
 * Generated source version: 2.2.4
 */

@WebFault(name = "ServiceLostException", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoServiceLostExceptionFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20220629181639L;

    private org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException;

    public UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoServiceLostExceptionFaultFaultMessage() {
        super();
    }

    public UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoServiceLostExceptionFaultFaultMessage(String message) {
        super(message);
    }

    public UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoServiceLostExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoServiceLostExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException) {
        super(message);
        this.serviceLostException = serviceLostException;
    }

    public UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoServiceLostExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException serviceLostException, Throwable cause) {
        super(message, cause);
        this.serviceLostException = serviceLostException;
    }

    public org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceLostException getFaultInfo() {
        return this.serviceLostException;
    }
}
