
package org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.4
 * Wed Jun 29 18:16:39 CST 2022
 * Generated source version: 2.2.4
 */

@WebFault(name = "ServiceExceptionDetail", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF.Service")
public class UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoServiceExceptionDetailFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20220629181639L;

    private org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail;

    public UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoServiceExceptionDetailFaultFaultMessage() {
        super();
    }

    public UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoServiceExceptionDetailFaultFaultMessage(String message) {
        super(message);
    }

    public UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoServiceExceptionDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoServiceExceptionDetailFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail) {
        super(message);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoServiceExceptionDetailFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail serviceExceptionDetail, Throwable cause) {
        super(message, cause);
        this.serviceExceptionDetail = serviceExceptionDetail;
    }

    public org.datacontract.schemas._2004._07.ufsoft_ubf.ServiceExceptionDetail getFaultInfo() {
        return this.serviceExceptionDetail;
    }
}
