
package org.ufida;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.4
 * Wed Jun 29 18:16:39 CST 2022
 * Generated source version: 2.2.4
 */

@WebFault(name = "ExceptionBase", targetNamespace = "http://schemas.datacontract.org/2004/07/UFSoft.UBF")
public class UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoExceptionBaseFaultFaultMessage extends Exception {
    public static final long serialVersionUID = 20220629181639L;

    private org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase;

    public UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoExceptionBaseFaultFaultMessage() {
        super();
    }

    public UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoExceptionBaseFaultFaultMessage(String message) {
        super(message);
    }

    public UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoExceptionBaseFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoExceptionBaseFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase) {
        super(message);
        this.exceptionBase = exceptionBase;
    }

    public UFIDAU9SzCusDevJARInterfaceSVISyncServiceDoExceptionBaseFaultFaultMessage(String message, org.datacontract.schemas._2004._07.ufsoft.ExceptionBase exceptionBase, Throwable cause) {
        super(message, cause);
        this.exceptionBase = exceptionBase;
    }

    public org.datacontract.schemas._2004._07.ufsoft.ExceptionBase getFaultInfo() {
        return this.exceptionBase;
    }
}
