
/*
 *
 */

package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import org.ufida.UFIDAU9SzCusDevJARInterfaceSVISyncService;

/**
 * This class was generated by Apache CXF 2.2.4
 * Wed Jun 29 18:16:39 CST 2022
 * Generated source version: 2.2.4
 */


@WebServiceClient(name = "SyncServiceStub",
        wsdlLocation = "http://192.168.2.233/U9/Services/UFIDA.U9.SzCusDev.JAR.InterfaceSV.ISyncService.svc?wsdl",
        targetNamespace = "http://tempuri.org/")
public class SyncServiceStub extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://tempuri.org/", "SyncServiceStub");
    public final static QName BasicHttpBindingUFIDAU9SzCusDevJARInterfaceSVISyncService = new QName("http://tempuri.org/", "BasicHttpBinding_UFIDA.U9.SzCusDev.JAR.InterfaceSV.ISyncService");

    static {
        URL url = null;
        try {
            url = new URL("http://192.168.2.233/U9/Services/UFIDA.U9.SzCusDev.JAR.InterfaceSV.ISyncService.svc?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://192.168.2.233/U9/Services/UFIDA.U9.SzCusDev.JAR.InterfaceSV.ISyncService.svc?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SyncServiceStub(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SyncServiceStub(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SyncServiceStub() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * @return returns UFIDAU9SzCusDevJARInterfaceSVISyncService
     */
    @WebEndpoint(name = "BasicHttpBinding_UFIDA.U9.SzCusDev.JAR.InterfaceSV.ISyncService")
    public UFIDAU9SzCusDevJARInterfaceSVISyncService getBasicHttpBindingUFIDAU9SzCusDevJARInterfaceSVISyncService() {
        return super.getPort(BasicHttpBindingUFIDAU9SzCusDevJARInterfaceSVISyncService, UFIDAU9SzCusDevJARInterfaceSVISyncService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns UFIDAU9SzCusDevJARInterfaceSVISyncService
     */
    @WebEndpoint(name = "BasicHttpBinding_UFIDA.U9.SzCusDev.JAR.InterfaceSV.ISyncService")
    public UFIDAU9SzCusDevJARInterfaceSVISyncService getBasicHttpBindingUFIDAU9SzCusDevJARInterfaceSVISyncService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingUFIDAU9SzCusDevJARInterfaceSVISyncService, UFIDAU9SzCusDevJARInterfaceSVISyncService.class, features);
    }

}
